theme: jekyll-theme-cayman
title: URS Portal
description: Unified Resonant Substrate Public Interface
include:
  - _includes/head-custom.html
include:
  - docs
baseurl: "/URS_PORTAL"  # Only if using GitHub Pages default domain
url: "https://bkg68w.github.io"

